## 启动端口
server:
  port: 8080

## 配置数据源的链接、用户名、密码等
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/7practice?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
